server:
  port: 8115
spring:
  application:
    name: admin-sever
  security:
    user:
      name: user
      password: admin
  boot:
    admin:
      ui:
        title: "Spring Boot Admin监控管理中心"
      notify:
        mail:
          from: 993203876@qq.com
          to: 1370707282@qq.com
          template: classpath:/META-INF/notifier.html
  mail:
    host: smtp.qq.com
    port: 25
    username: 993203876@qq.com
    password: mjtbinvnbmqwbahh
    protocol: smtp
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/,http://localhost:8001/eureka/
info:
  version: @project.version@
