eureka:
  client:
    service-url:
      defaultZone: http://peer1:8000/eureka/,http://peer2:8001/eureka/
spring:
  application:
    name: spring-cloud-gateway
  profiles:
    active: use
  cloud:
    gateway:
      routes:
      - id: path_route #路径匹配
        uri: http://localhost:8108
        predicates:
        - Path=/eureka-producer
server:
  port: 8109



