eureka:
  client:
    service-url:
      defaultZone: http://peer1:8000/eureka/,http://peer2:8001/eureka/
spring:
  application:
    name: spring-cloud-gateway
  profiles:
    active: use
  cloud:
    gateway:
      routes:
      - id: consumer #路径匹配
        uri: http://localhost:8897
        predicates:
        - Path=/consumer-api/**
        filters:
        - RewritePath=/consumer-api/(?<segment>.*), /$\{segment}
      - id: producer
        uri: lb://eureka-producer
        predicates:
        - Path=/eureka-producer/**
        filters:
        - RewritePath=/eureka-producer/(?<segment>.*), /$\{segment}
  zipkin:
    sender:
      type: web
    base-url: http://localhost:9411/
  sleuth:
      sampler:
        probability: 1.0
server:
  port: 8109