server:
  port: 8107
spring:
  application:
    name: zuul-swagger-butler

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/,http://localhost:8001/eureka/
swagger:
  butler:
    auto-generate-from-zuul-routes: true
