spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jay
    username: root
    password: '0817'
server:
  port: 8113
logging:
  level:
    com.ttyc.doc.cache.helper: debug
mybatis:
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
  type-aliases-package: com.ttyc.doc.cache.helper