/*
 * This file is generated by jOOQ.
*/
package com.example.domain.jooq;


import com.example.domain.jooq.tables.Address;
import com.example.domain.jooq.tables.CarOpLog;
import com.example.domain.jooq.tables.JobExecutionLog;
import com.example.domain.jooq.tables.JobStatusTraceLog;
import com.example.domain.jooq.tables.Student;
import com.example.domain.jooq.tables.Test;
import com.example.domain.jooq.tables.User;
import com.example.domain.jooq.tables.records.AddressRecord;
import com.example.domain.jooq.tables.records.CarOpLogRecord;
import com.example.domain.jooq.tables.records.JobExecutionLogRecord;
import com.example.domain.jooq.tables.records.JobStatusTraceLogRecord;
import com.example.domain.jooq.tables.records.StudentRecord;
import com.example.domain.jooq.tables.records.TestRecord;
import com.example.domain.jooq.tables.records.UserRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;
import org.jooq.types.UInteger;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>jay</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<AddressRecord, UInteger> IDENTITY_ADDRESS = Identities0.IDENTITY_ADDRESS;
    public static final Identity<CarOpLogRecord, Long> IDENTITY_CAR_OP_LOG = Identities0.IDENTITY_CAR_OP_LOG;
    public static final Identity<StudentRecord, UInteger> IDENTITY_STUDENT = Identities0.IDENTITY_STUDENT;
    public static final Identity<TestRecord, UInteger> IDENTITY_TEST = Identities0.IDENTITY_TEST;
    public static final Identity<UserRecord, UInteger> IDENTITY_USER = Identities0.IDENTITY_USER;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AddressRecord> KEY_ADDRESS_PRIMARY = UniqueKeys0.KEY_ADDRESS_PRIMARY;
    public static final UniqueKey<CarOpLogRecord> KEY_CAR_OP_LOG_PRIMARY = UniqueKeys0.KEY_CAR_OP_LOG_PRIMARY;
    public static final UniqueKey<CarOpLogRecord> KEY_CAR_OP_LOG_IDX_OP_ID = UniqueKeys0.KEY_CAR_OP_LOG_IDX_OP_ID;
    public static final UniqueKey<JobExecutionLogRecord> KEY_JOB_EXECUTION_LOG_PRIMARY = UniqueKeys0.KEY_JOB_EXECUTION_LOG_PRIMARY;
    public static final UniqueKey<JobStatusTraceLogRecord> KEY_JOB_STATUS_TRACE_LOG_PRIMARY = UniqueKeys0.KEY_JOB_STATUS_TRACE_LOG_PRIMARY;
    public static final UniqueKey<StudentRecord> KEY_STUDENT_PRIMARY = UniqueKeys0.KEY_STUDENT_PRIMARY;
    public static final UniqueKey<TestRecord> KEY_TEST_PRIMARY = UniqueKeys0.KEY_TEST_PRIMARY;
    public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = UniqueKeys0.KEY_USER_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<AddressRecord, UInteger> IDENTITY_ADDRESS = Internal.createIdentity(Address.ADDRESS, Address.ADDRESS.ID);
        public static Identity<CarOpLogRecord, Long> IDENTITY_CAR_OP_LOG = Internal.createIdentity(CarOpLog.CAR_OP_LOG, CarOpLog.CAR_OP_LOG.ID);
        public static Identity<StudentRecord, UInteger> IDENTITY_STUDENT = Internal.createIdentity(Student.STUDENT, Student.STUDENT.ID);
        public static Identity<TestRecord, UInteger> IDENTITY_TEST = Internal.createIdentity(Test.TEST, Test.TEST.ID);
        public static Identity<UserRecord, UInteger> IDENTITY_USER = Internal.createIdentity(User.USER, User.USER.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<AddressRecord> KEY_ADDRESS_PRIMARY = Internal.createUniqueKey(Address.ADDRESS, "KEY_address_PRIMARY", Address.ADDRESS.ID);
        public static final UniqueKey<CarOpLogRecord> KEY_CAR_OP_LOG_PRIMARY = Internal.createUniqueKey(CarOpLog.CAR_OP_LOG, "KEY_car_op_log_PRIMARY", CarOpLog.CAR_OP_LOG.ID);
        public static final UniqueKey<CarOpLogRecord> KEY_CAR_OP_LOG_IDX_OP_ID = Internal.createUniqueKey(CarOpLog.CAR_OP_LOG, "KEY_car_op_log_idx_op_id", CarOpLog.CAR_OP_LOG.OP_ID);
        public static final UniqueKey<JobExecutionLogRecord> KEY_JOB_EXECUTION_LOG_PRIMARY = Internal.createUniqueKey(JobExecutionLog.JOB_EXECUTION_LOG, "KEY_JOB_EXECUTION_LOG_PRIMARY", JobExecutionLog.JOB_EXECUTION_LOG.ID);
        public static final UniqueKey<JobStatusTraceLogRecord> KEY_JOB_STATUS_TRACE_LOG_PRIMARY = Internal.createUniqueKey(JobStatusTraceLog.JOB_STATUS_TRACE_LOG, "KEY_JOB_STATUS_TRACE_LOG_PRIMARY", JobStatusTraceLog.JOB_STATUS_TRACE_LOG.ID);
        public static final UniqueKey<StudentRecord> KEY_STUDENT_PRIMARY = Internal.createUniqueKey(Student.STUDENT, "KEY_student_PRIMARY", Student.STUDENT.ID);
        public static final UniqueKey<TestRecord> KEY_TEST_PRIMARY = Internal.createUniqueKey(Test.TEST, "KEY_test_PRIMARY", Test.TEST.ID);
        public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = Internal.createUniqueKey(User.USER, "KEY_user_PRIMARY", User.USER.ID);
    }
}
