/*
 * This file is generated by jOOQ.
*/
package com.example.domain.jooq;


import com.example.domain.jooq.tables.Address;
import com.example.domain.jooq.tables.CarOpLog;
import com.example.domain.jooq.tables.JobExecutionLog;
import com.example.domain.jooq.tables.JobStatusTraceLog;
import com.example.domain.jooq.tables.Student;
import com.example.domain.jooq.tables.Test;
import com.example.domain.jooq.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in jay
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>jay.address</code>.
     */
    public static final Address ADDRESS = com.example.domain.jooq.tables.Address.ADDRESS;

    /**
     * 车辆操作记录
     */
    public static final CarOpLog CAR_OP_LOG = com.example.domain.jooq.tables.CarOpLog.CAR_OP_LOG;

    /**
     * The table <code>jay.JOB_EXECUTION_LOG</code>.
     */
    public static final JobExecutionLog JOB_EXECUTION_LOG = com.example.domain.jooq.tables.JobExecutionLog.JOB_EXECUTION_LOG;

    /**
     * The table <code>jay.JOB_STATUS_TRACE_LOG</code>.
     */
    public static final JobStatusTraceLog JOB_STATUS_TRACE_LOG = com.example.domain.jooq.tables.JobStatusTraceLog.JOB_STATUS_TRACE_LOG;

    /**
     * The table <code>jay.student</code>.
     */
    public static final Student STUDENT = com.example.domain.jooq.tables.Student.STUDENT;

    /**
     * The table <code>jay.test</code>.
     */
    public static final Test TEST = com.example.domain.jooq.tables.Test.TEST;

    /**
     * The table <code>jay.user</code>.
     */
    public static final User USER = com.example.domain.jooq.tables.User.USER;
}
