spring:
  application:
    name: config-center-git
  cloud:
    config:
      server:
        git:
          uri: http://gitlab.corp.songguo7.com:8360/yangjie/spring-cloud-config-center.git
          default-label: master
server:
  port: 8200
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8000/eureka/,http://peer2:8001/eureka/