server:
  port: 8897
spring:
  application:
    name: consumer-api
  zipkin:
      sender:
        type: web
      base-url: http://localhost:9411/
      enabled: false
  sleuth:
    sampler:
      probability: 1.0
  #server:

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/,http://localhost:8001/eureka/
#    healthcheck:
#      enabled: true 版本变化？
feign:
  httpclient:
    enable: true

swagger:
  base-package: com.ttyc.consumer.feign
  enabled: true
