server:
  port: 8897
spring:
  application:
    name: consumer-api
  zipkin:
      sender:
        type: web
      base-url: http://localhost:9411/
      enabled: false
  sleuth:
    sampler:
      probability: 1.0
  #server:

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/,http://localhost:8001/eureka/
#    healthcheck:
#      enabled: true 版本变化？
feign:
  httpclient:
    enable: true

swagger:
  base-package: com.ttyc.consumer.feign
  enabled: true

#超時
consumer-api:
  ribbon:
    ReadTimeout: 2000
    ConnectTimeout: 1000
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 1

ribbon:
  eager-load:
    enabled: true
    clients: eureka-producer

xpack.notification.email.account:
  qq_account:
    profile: qq
    smtp:
      auth: true
      starttls.enable: true
      host: smtp.qq.com
      user: 993203876@qq.com
      port: 587
      password: cjwvmgokutikbcjg


