/*
 * This file is generated by jOOQ.
*/
package com.example.domain.jooq.tables.records;


import com.example.domain.jooq.tables.JobExecutionLog;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JobExecutionLogRecord extends UpdatableRecordImpl<JobExecutionLogRecord> implements Record11<String, String, String, String, String, Integer, String, String, Integer, Timestamp, Timestamp> {

    private static final long serialVersionUID = -822904979;

    /**
     * Setter for <code>jay.JOB_EXECUTION_LOG.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>jay.JOB_EXECUTION_LOG.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>jay.JOB_EXECUTION_LOG.job_name</code>.
     */
    public void setJobName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>jay.JOB_EXECUTION_LOG.job_name</code>.
     */
    public String getJobName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>jay.JOB_EXECUTION_LOG.task_id</code>.
     */
    public void setTaskId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>jay.JOB_EXECUTION_LOG.task_id</code>.
     */
    public String getTaskId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>jay.JOB_EXECUTION_LOG.hostname</code>.
     */
    public void setHostname(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>jay.JOB_EXECUTION_LOG.hostname</code>.
     */
    public String getHostname() {
        return (String) get(3);
    }

    /**
     * Setter for <code>jay.JOB_EXECUTION_LOG.ip</code>.
     */
    public void setIp(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>jay.JOB_EXECUTION_LOG.ip</code>.
     */
    public String getIp() {
        return (String) get(4);
    }

    /**
     * Setter for <code>jay.JOB_EXECUTION_LOG.sharding_item</code>.
     */
    public void setShardingItem(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>jay.JOB_EXECUTION_LOG.sharding_item</code>.
     */
    public Integer getShardingItem() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>jay.JOB_EXECUTION_LOG.execution_source</code>.
     */
    public void setExecutionSource(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>jay.JOB_EXECUTION_LOG.execution_source</code>.
     */
    public String getExecutionSource() {
        return (String) get(6);
    }

    /**
     * Setter for <code>jay.JOB_EXECUTION_LOG.failure_cause</code>.
     */
    public void setFailureCause(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>jay.JOB_EXECUTION_LOG.failure_cause</code>.
     */
    public String getFailureCause() {
        return (String) get(7);
    }

    /**
     * Setter for <code>jay.JOB_EXECUTION_LOG.is_success</code>.
     */
    public void setIsSuccess(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>jay.JOB_EXECUTION_LOG.is_success</code>.
     */
    public Integer getIsSuccess() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>jay.JOB_EXECUTION_LOG.start_time</code>.
     */
    public void setStartTime(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>jay.JOB_EXECUTION_LOG.start_time</code>.
     */
    public Timestamp getStartTime() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>jay.JOB_EXECUTION_LOG.complete_time</code>.
     */
    public void setCompleteTime(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>jay.JOB_EXECUTION_LOG.complete_time</code>.
     */
    public Timestamp getCompleteTime() {
        return (Timestamp) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<String, String, String, String, String, Integer, String, String, Integer, Timestamp, Timestamp> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<String, String, String, String, String, Integer, String, String, Integer, Timestamp, Timestamp> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return JobExecutionLog.JOB_EXECUTION_LOG.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return JobExecutionLog.JOB_EXECUTION_LOG.JOB_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return JobExecutionLog.JOB_EXECUTION_LOG.TASK_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return JobExecutionLog.JOB_EXECUTION_LOG.HOSTNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return JobExecutionLog.JOB_EXECUTION_LOG.IP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return JobExecutionLog.JOB_EXECUTION_LOG.SHARDING_ITEM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return JobExecutionLog.JOB_EXECUTION_LOG.EXECUTION_SOURCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return JobExecutionLog.JOB_EXECUTION_LOG.FAILURE_CAUSE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return JobExecutionLog.JOB_EXECUTION_LOG.IS_SUCCESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return JobExecutionLog.JOB_EXECUTION_LOG.START_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return JobExecutionLog.JOB_EXECUTION_LOG.COMPLETE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getJobName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getTaskId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getHostname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getIp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getShardingItem();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getExecutionSource();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getFailureCause();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getIsSuccess();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component10() {
        return getStartTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component11() {
        return getCompleteTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getJobName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTaskId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getHostname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getIp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getShardingItem();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getExecutionSource();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getFailureCause();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getIsSuccess();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getStartTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getCompleteTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobExecutionLogRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobExecutionLogRecord value2(String value) {
        setJobName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobExecutionLogRecord value3(String value) {
        setTaskId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobExecutionLogRecord value4(String value) {
        setHostname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobExecutionLogRecord value5(String value) {
        setIp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobExecutionLogRecord value6(Integer value) {
        setShardingItem(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobExecutionLogRecord value7(String value) {
        setExecutionSource(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobExecutionLogRecord value8(String value) {
        setFailureCause(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobExecutionLogRecord value9(Integer value) {
        setIsSuccess(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobExecutionLogRecord value10(Timestamp value) {
        setStartTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobExecutionLogRecord value11(Timestamp value) {
        setCompleteTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobExecutionLogRecord values(String value1, String value2, String value3, String value4, String value5, Integer value6, String value7, String value8, Integer value9, Timestamp value10, Timestamp value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JobExecutionLogRecord
     */
    public JobExecutionLogRecord() {
        super(JobExecutionLog.JOB_EXECUTION_LOG);
    }

    /**
     * Create a detached, initialised JobExecutionLogRecord
     */
    public JobExecutionLogRecord(String id, String jobName, String taskId, String hostname, String ip, Integer shardingItem, String executionSource, String failureCause, Integer isSuccess, Timestamp startTime, Timestamp completeTime) {
        super(JobExecutionLog.JOB_EXECUTION_LOG);

        set(0, id);
        set(1, jobName);
        set(2, taskId);
        set(3, hostname);
        set(4, ip);
        set(5, shardingItem);
        set(6, executionSource);
        set(7, failureCause);
        set(8, isSuccess);
        set(9, startTime);
        set(10, completeTime);
    }
}
