/*
 * This file is generated by jOOQ.
*/
package com.example.domain.jooq.tables.records;


import com.example.domain.jooq.tables.JobStatusTraceLog;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JobStatusTraceLogRecord extends UpdatableRecordImpl<JobStatusTraceLogRecord> implements Record11<String, String, String, String, String, String, String, String, String, String, Timestamp> {

    private static final long serialVersionUID = -1356404645;

    /**
     * Setter for <code>jay.JOB_STATUS_TRACE_LOG.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>jay.JOB_STATUS_TRACE_LOG.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>jay.JOB_STATUS_TRACE_LOG.job_name</code>.
     */
    public void setJobName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>jay.JOB_STATUS_TRACE_LOG.job_name</code>.
     */
    public String getJobName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>jay.JOB_STATUS_TRACE_LOG.original_task_id</code>.
     */
    public void setOriginalTaskId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>jay.JOB_STATUS_TRACE_LOG.original_task_id</code>.
     */
    public String getOriginalTaskId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>jay.JOB_STATUS_TRACE_LOG.task_id</code>.
     */
    public void setTaskId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>jay.JOB_STATUS_TRACE_LOG.task_id</code>.
     */
    public String getTaskId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>jay.JOB_STATUS_TRACE_LOG.slave_id</code>.
     */
    public void setSlaveId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>jay.JOB_STATUS_TRACE_LOG.slave_id</code>.
     */
    public String getSlaveId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>jay.JOB_STATUS_TRACE_LOG.source</code>.
     */
    public void setSource(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>jay.JOB_STATUS_TRACE_LOG.source</code>.
     */
    public String getSource() {
        return (String) get(5);
    }

    /**
     * Setter for <code>jay.JOB_STATUS_TRACE_LOG.execution_type</code>.
     */
    public void setExecutionType(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>jay.JOB_STATUS_TRACE_LOG.execution_type</code>.
     */
    public String getExecutionType() {
        return (String) get(6);
    }

    /**
     * Setter for <code>jay.JOB_STATUS_TRACE_LOG.sharding_item</code>.
     */
    public void setShardingItem(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>jay.JOB_STATUS_TRACE_LOG.sharding_item</code>.
     */
    public String getShardingItem() {
        return (String) get(7);
    }

    /**
     * Setter for <code>jay.JOB_STATUS_TRACE_LOG.state</code>.
     */
    public void setState(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>jay.JOB_STATUS_TRACE_LOG.state</code>.
     */
    public String getState() {
        return (String) get(8);
    }

    /**
     * Setter for <code>jay.JOB_STATUS_TRACE_LOG.message</code>.
     */
    public void setMessage(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>jay.JOB_STATUS_TRACE_LOG.message</code>.
     */
    public String getMessage() {
        return (String) get(9);
    }

    /**
     * Setter for <code>jay.JOB_STATUS_TRACE_LOG.creation_time</code>.
     */
    public void setCreationTime(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>jay.JOB_STATUS_TRACE_LOG.creation_time</code>.
     */
    public Timestamp getCreationTime() {
        return (Timestamp) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<String, String, String, String, String, String, String, String, String, String, Timestamp> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<String, String, String, String, String, String, String, String, String, String, Timestamp> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return JobStatusTraceLog.JOB_STATUS_TRACE_LOG.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return JobStatusTraceLog.JOB_STATUS_TRACE_LOG.JOB_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return JobStatusTraceLog.JOB_STATUS_TRACE_LOG.ORIGINAL_TASK_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return JobStatusTraceLog.JOB_STATUS_TRACE_LOG.TASK_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return JobStatusTraceLog.JOB_STATUS_TRACE_LOG.SLAVE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return JobStatusTraceLog.JOB_STATUS_TRACE_LOG.SOURCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return JobStatusTraceLog.JOB_STATUS_TRACE_LOG.EXECUTION_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return JobStatusTraceLog.JOB_STATUS_TRACE_LOG.SHARDING_ITEM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return JobStatusTraceLog.JOB_STATUS_TRACE_LOG.STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return JobStatusTraceLog.JOB_STATUS_TRACE_LOG.MESSAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return JobStatusTraceLog.JOB_STATUS_TRACE_LOG.CREATION_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getJobName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getOriginalTaskId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getTaskId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getSlaveId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getSource();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getExecutionType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getShardingItem();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getMessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component11() {
        return getCreationTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getJobName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getOriginalTaskId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getTaskId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getSlaveId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getSource();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getExecutionType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getShardingItem();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getMessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getCreationTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobStatusTraceLogRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobStatusTraceLogRecord value2(String value) {
        setJobName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobStatusTraceLogRecord value3(String value) {
        setOriginalTaskId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobStatusTraceLogRecord value4(String value) {
        setTaskId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobStatusTraceLogRecord value5(String value) {
        setSlaveId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobStatusTraceLogRecord value6(String value) {
        setSource(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobStatusTraceLogRecord value7(String value) {
        setExecutionType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobStatusTraceLogRecord value8(String value) {
        setShardingItem(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobStatusTraceLogRecord value9(String value) {
        setState(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobStatusTraceLogRecord value10(String value) {
        setMessage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobStatusTraceLogRecord value11(Timestamp value) {
        setCreationTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobStatusTraceLogRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, Timestamp value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JobStatusTraceLogRecord
     */
    public JobStatusTraceLogRecord() {
        super(JobStatusTraceLog.JOB_STATUS_TRACE_LOG);
    }

    /**
     * Create a detached, initialised JobStatusTraceLogRecord
     */
    public JobStatusTraceLogRecord(String id, String jobName, String originalTaskId, String taskId, String slaveId, String source, String executionType, String shardingItem, String state, String message, Timestamp creationTime) {
        super(JobStatusTraceLog.JOB_STATUS_TRACE_LOG);

        set(0, id);
        set(1, jobName);
        set(2, originalTaskId);
        set(3, taskId);
        set(4, slaveId);
        set(5, source);
        set(6, executionType);
        set(7, shardingItem);
        set(8, state);
        set(9, message);
        set(10, creationTime);
    }
}
