server:
  port: 8113
spring:
  application:
    name: sidecar-go
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/,http://localhost:8001/eureka/
sidecar:
  port: 8061
  health-uri: http://localhost:8061/health.json

