spring:
  application:
    name: sleuth-feign-consumer
  sleuth:
    sampler:
      probability: 1.0
    http:
      legacy:
        enabled: true
    enabled: true
  zipkin:
    service:
      name: sleuth_consumer
    sender:
      type: kafka
    locator:
      discovery:
        enabled: true
    base-url: http://dev.zipkin.songguo7.com:9411/
  kafka:
    bootstrap-servers: redis01.test.songguo7.com.ucb:9192,redis01.test.songguo7.com.ucb:9292,redis01.test.songguo7.com.ucb:9392
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8000/eureka/
server:
  port: 8111
logging:
  level:
    root: info

