spring:
  application:
    name: sleuth-feign-consumer
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    service:
      name: sleuth_consumer
    base-url: http://localhost:9411
    sender:
      type: web
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8000/eureka/,http://peer2:8001/eureka/
server:
  port: 8111