spring:
  application:
    name: sleuth-feign-consumer
  sleuth:
    sampler:
      probability: 1.0
    http:
      legacy:
        enabled: true
    enabled: true
  zipkin:
    service:
      name: sleuth_consumer
    sender:
      type: kafka
    locator:
      discovery:
        enabled: true
    base-url: http://localhost:9411/
  kafka:
    bootstrap-servers: localhost:9092
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8000/eureka/
server:
  port: 8111
logging:
  level:
    root: info

