spring:
  application:
    name: sleuth-feign-consumer
  sleuth:
    sampler:
      probability: 1.0
    http:
      legacy:
        enabled: true
    enabled: true
  zipkin:
    service:
      name: sleuth_consumer
    base-url: http://localhost:9411
    sender:
      type: web
    locator:
      discovery:
        enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8000/eureka/,http://peer2:8001/eureka/
server:
  port: 8111