server:
  port: 8108
spring:
  application:
    name: sleuth-client
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    service-url:
      default-zone: http://peer1:8000/eureka/,http://peer2:8001/eureka/
