spring:
  application:
    name: sleuth-feign-producer
  zipkin:
      base-url: http://localhost:9411
      sender:
        type: web
  sleuth:
    sampler:
      probability: 1.0
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
#  datasource:
#    url: jdbc:mysql://localhost:3306/aicar
#    username: root
#    password: 0817
#    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8000/eureka/,http://peer2:8001/eureka/
server:
  port: 8110
logging:
  level:
   root: info

