spring:
  application:
    name: sleuth-feign-producer
  zipkin:
      #base-url: http://localhost:9411
      service:
        name: sleuth-producer
      sender:
        type: kafka
      kafka:
        topic: zipkin-trace
  sleuth:
    sampler:
      probability: 1.0
  kafka:
    bootstrap-servers: 10.9.91.230:9092,10.9.155.143:9092
#eureka:
#  client:
#    service-url:
#      defaultZone: http://peer1:8000/eureka/,http://peer2:8001/eureka/

server:
  port: 8110
logging:
  level:
   root: info