spring:
  application:
    name: sleuth-feign-producer
  zipkin:
      base-url: http://localhost:9411
      service:
        name: sleuth-producer
      sender:
        type: web
      locator:
        discovery:
          enabled: true

  sleuth:
    sampler:
      probability: 1.0
    enabled: true
    http:
      legacy:
        enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8000/eureka/,http://peer2:8001/eureka/

server:
  port: 8110
logging:
  level:
   root: info