spring:
  application:
    name: sleuth-feign-producer
  zipkin:
    service:
      name: sleuth-producer
    sender:
      type: kafka
    base-url: http://dev.zipkin.songguo7.com:9411/
  sleuth:
    sampler:
      probability: 1.0
    enabled: true
    http:
      legacy:
        enabled: true
  kafka:
    bootstrap-servers: redis01.test.songguo7.com.ucb:9192,redis01.test.songguo7.com.ucb:9292,redis01.test.songguo7.com.ucb:9392
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8000/eureka/

server:
  port: 8110
logging:
  level:
   root: info