/*
 * This file is generated by jOOQ.
*/
package com.example.domain.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Address implements Serializable {

    private static final long serialVersionUID = 640871150;

    private UInteger id;
    private Integer  city;
    private Integer  town;
    private Integer  uid;

    public Address() {}

    public Address(Address value) {
        this.id = value.id;
        this.city = value.city;
        this.town = value.town;
        this.uid = value.uid;
    }

    public Address(
        UInteger id,
        Integer  city,
        Integer  town,
        Integer  uid
    ) {
        this.id = id;
        this.city = city;
        this.town = town;
        this.uid = uid;
    }

    public UInteger getId() {
        return this.id;
    }

    public void setId(UInteger id) {
        this.id = id;
    }

    public Integer getCity() {
        return this.city;
    }

    public void setCity(Integer city) {
        this.city = city;
    }

    public Integer getTown() {
        return this.town;
    }

    public void setTown(Integer town) {
        this.town = town;
    }

    public Integer getUid() {
        return this.uid;
    }

    public void setUid(Integer uid) {
        this.uid = uid;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Address (");

        sb.append(id);
        sb.append(", ").append(city);
        sb.append(", ").append(town);
        sb.append(", ").append(uid);

        sb.append(")");
        return sb.toString();
    }
}
