/*
 * This file is generated by jOOQ.
*/
package com.example.domain.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 车辆操作记录
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CarOpLog implements Serializable {

    private static final long serialVersionUID = -302741736;

    private Long      id;
    private Boolean   userType;
    private Long      userId;
    private String    carSn;
    private Boolean   opType;
    private Boolean   opResult;
    private Boolean   clientType;
    private Timestamp createTime;
    private Timestamp updateTime;
    private Boolean   channelType;
    private Boolean   carStatus;
    private String    snapShot;
    private String    failReason;
    private Long      opId;
    private String    orderSn;

    public CarOpLog() {}

    public CarOpLog(CarOpLog value) {
        this.id = value.id;
        this.userType = value.userType;
        this.userId = value.userId;
        this.carSn = value.carSn;
        this.opType = value.opType;
        this.opResult = value.opResult;
        this.clientType = value.clientType;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
        this.channelType = value.channelType;
        this.carStatus = value.carStatus;
        this.snapShot = value.snapShot;
        this.failReason = value.failReason;
        this.opId = value.opId;
        this.orderSn = value.orderSn;
    }

    public CarOpLog(
        Long      id,
        Boolean   userType,
        Long      userId,
        String    carSn,
        Boolean   opType,
        Boolean   opResult,
        Boolean   clientType,
        Timestamp createTime,
        Timestamp updateTime,
        Boolean   channelType,
        Boolean   carStatus,
        String    snapShot,
        String    failReason,
        Long      opId,
        String    orderSn
    ) {
        this.id = id;
        this.userType = userType;
        this.userId = userId;
        this.carSn = carSn;
        this.opType = opType;
        this.opResult = opResult;
        this.clientType = clientType;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.channelType = channelType;
        this.carStatus = carStatus;
        this.snapShot = snapShot;
        this.failReason = failReason;
        this.opId = opId;
        this.orderSn = orderSn;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Boolean getUserType() {
        return this.userType;
    }

    public void setUserType(Boolean userType) {
        this.userType = userType;
    }

    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getCarSn() {
        return this.carSn;
    }

    public void setCarSn(String carSn) {
        this.carSn = carSn;
    }

    public Boolean getOpType() {
        return this.opType;
    }

    public void setOpType(Boolean opType) {
        this.opType = opType;
    }

    public Boolean getOpResult() {
        return this.opResult;
    }

    public void setOpResult(Boolean opResult) {
        this.opResult = opResult;
    }

    public Boolean getClientType() {
        return this.clientType;
    }

    public void setClientType(Boolean clientType) {
        this.clientType = clientType;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    public Boolean getChannelType() {
        return this.channelType;
    }

    public void setChannelType(Boolean channelType) {
        this.channelType = channelType;
    }

    public Boolean getCarStatus() {
        return this.carStatus;
    }

    public void setCarStatus(Boolean carStatus) {
        this.carStatus = carStatus;
    }

    public String getSnapShot() {
        return this.snapShot;
    }

    public void setSnapShot(String snapShot) {
        this.snapShot = snapShot;
    }

    public String getFailReason() {
        return this.failReason;
    }

    public void setFailReason(String failReason) {
        this.failReason = failReason;
    }

    public Long getOpId() {
        return this.opId;
    }

    public void setOpId(Long opId) {
        this.opId = opId;
    }

    public String getOrderSn() {
        return this.orderSn;
    }

    public void setOrderSn(String orderSn) {
        this.orderSn = orderSn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CarOpLog (");

        sb.append(id);
        sb.append(", ").append(userType);
        sb.append(", ").append(userId);
        sb.append(", ").append(carSn);
        sb.append(", ").append(opType);
        sb.append(", ").append(opResult);
        sb.append(", ").append(clientType);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(channelType);
        sb.append(", ").append(carStatus);
        sb.append(", ").append(snapShot);
        sb.append(", ").append(failReason);
        sb.append(", ").append(opId);
        sb.append(", ").append(orderSn);

        sb.append(")");
        return sb.toString();
    }
}
