/*
 * This file is generated by jOOQ.
*/
package com.example.domain.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Student implements Serializable {

    private static final long serialVersionUID = -410610407;

    private UInteger id;
    private String   name;
    private String   course;
    private Integer  score;

    public Student() {}

    public Student(Student value) {
        this.id = value.id;
        this.name = value.name;
        this.course = value.course;
        this.score = value.score;
    }

    public Student(
        UInteger id,
        String   name,
        String   course,
        Integer  score
    ) {
        this.id = id;
        this.name = name;
        this.course = course;
        this.score = score;
    }

    public UInteger getId() {
        return this.id;
    }

    public void setId(UInteger id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCourse() {
        return this.course;
    }

    public void setCourse(String course) {
        this.course = course;
    }

    public Integer getScore() {
        return this.score;
    }

    public void setScore(Integer score) {
        this.score = score;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Student (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(course);
        sb.append(", ").append(score);

        sb.append(")");
        return sb.toString();
    }
}
