/*
 * This file is generated by jOOQ.
*/
package com.example.domain.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Test implements Serializable {

    private static final long serialVersionUID = -51101626;

    private UInteger id;
    private String   name;
    private Integer  java;
    private Integer  mysql;
    private Integer  kafka;

    public Test() {}

    public Test(Test value) {
        this.id = value.id;
        this.name = value.name;
        this.java = value.java;
        this.mysql = value.mysql;
        this.kafka = value.kafka;
    }

    public Test(
        UInteger id,
        String   name,
        Integer  java,
        Integer  mysql,
        Integer  kafka
    ) {
        this.id = id;
        this.name = name;
        this.java = java;
        this.mysql = mysql;
        this.kafka = kafka;
    }

    public UInteger getId() {
        return this.id;
    }

    public void setId(UInteger id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getJava() {
        return this.java;
    }

    public void setJava(Integer java) {
        this.java = java;
    }

    public Integer getMysql() {
        return this.mysql;
    }

    public void setMysql(Integer mysql) {
        this.mysql = mysql;
    }

    public Integer getKafka() {
        return this.kafka;
    }

    public void setKafka(Integer kafka) {
        this.kafka = kafka;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Test (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(java);
        sb.append(", ").append(mysql);
        sb.append(", ").append(kafka);

        sb.append(")");
        return sb.toString();
    }
}
