server:
  port: 8109
  error:
    path: /error
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: '0817'
  mvc:
    message-codes-resolver-format: PREFIX_ERROR_CODE
    contentnegotiation:
      favor-parameter: true
      parameter-name: type
      media-types:
        json: application/json
        xml: application/xml
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
  type-aliases-package: com.ttyc.spring.base.model


