server:
  port: 8116
spring:
  boot:
    admin:
      client:
        url: http://localhost:8115
        instance:
          metadata:
            tags:
              content: mesh
  security:
    user:
      name: user
      password: admin
  application:
    name: admin-client

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  file: client.log
info:
  version: @project.version@
  tags:
    title: mosi