server:
  port: 8116
spring:
  boot:
    admin:
      client:
        url: http://localhost:8115 # 必须写http://
  security:
    user:
      name: user
      password: admin
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
logging:
  file: client.log
info:
  version: @project.version@