server:
  port: 8116
spring:
  cloud:
    discovery:
      client:
        simple:
          instances:
            test:
              - uri: http://localhost:8115
                metadata:
                  management.context-path: /actuator
  security:
      user:
        name: user
        password: admin
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
logging:
  file: client.log
info:
  version: @project.version@
  tags:
    title: mosi