server:
  port: 8116
spring:
  boot:
    admin:
      client:
        url: http://localhost:8115
        instance:
          metadata:
            tags:
              content: mesh
          name: ${spring.application.name}
          prefer-ip: true
        enabled: true
        username: user
        password: admin
        connect-timeout: 5000ms
        read-timeout: 5000ms
        period: 10000ms # 每10秒注册一次
        auto-registration: true #应用启动后自动开始注册
  application:
    name: admin-client

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  file: client.log
info:
  version: @project.version@
  tags:
    title: mosi