server:
  port: 8102
spring:
  application:
    name: consumer-ribbon
  cloud:
    loadbalancer:
      retry:
        enabled: true

# ribbon retry
eureka-consumer-ribbon:
  ConnectTimeout: 250
  ReadTimeout: 1000
  OkToRetryOnAllOperations: true
  MaxAutoRetriesNextServer: 2
  MaxAutoRetries: 1
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000


# regist center
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10 # 每10s发送心跳包
    lease-expiration-duration-in-seconds: 30 #过期时间
swagger:
  base-package: com.ttyc.consumer.ribbon
  enabled: true


