eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/,http://localhost:8001/eureka/
spring:
  application:
    name: eureka-producer

---
server:
  port: 8100
spring:
  profiles: serviceA

---
server:
  port: 8108
spring:
  profiles: serviceB


