server:
  port: 8100
spring:
  application:
    name: eureka-producer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
#    healthcheck:
#      enabled: true 版本变化？

